### ISSUE TITLE
Suggestions for organizing input arguments that are related to each other

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#102]
Prompted by #100 (see the section "Potential problems not addressed by this PR"). Here is my viewpoint and preferred solution. Other ideas/discussion also welcome.

## Basic idea
In cases where there are variables/values that all refer to the same conceptual thing (an astronomical object, a passband, etc.) and they need to be passed in to several different functions, I prefer to tie those values together into one python object at the very beginning. This helps prevent them from getting accidentally separated from each other and/or jumbled in with the wrong astro-object/passband/etc. (e.g., when lists get out of alignment with each other). Self-contained arguments for a single object also helps make them safe for parallel processing. 

I often find that using [`collections.namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) is the simplest route. (Related to [`typing.NamedTuple`](https://docs.python.org/3/library/typing.html#typing.NamedTuple) which is useful if you want to add documentation to the class definition.)

## An example
For the multiband light curve notebook, the data structure for the input arguments could look like the following. (We probably don't want to change that notebook at this point, but this is a concrete example I'll use to give ideas for future notebooks.)

```python
from collections import namedtuple

# create a class to hold the input arguments for a single object
SampleObject = namedtuple("SampleObject", ["id", "coords", "label", "name"])
```

`SampleObject` is a subclass of a regular tuple that has the additional benefit that elements/attributes can be access by name using the `.` notation (like `singleobj.coords`). It would then be used like this:

```python
# construct a list of objects
# the actual implementation would be different, but here's some pseudocode to see what the list looks like:
objects_list = [
    SampleObject(id=<id_object0>, coords=<coords_object0>, label=<label_object0>, name=<name_object0>),
    SampleObject(id=<id_object1>, coords=<coords_object1>, label=<label_object1>, name=<name_object1>),
    ...
]

# iterate over the list and access the attributes of each `SampleObject` (basic access example)
for singleobj in objects_list:
    singleobj.id  # use anywhere the objectid is needed
    singleobj.coords  # use anywhere the object's coords are needed
   # etc.
```

Note:  Never use "`object`" as a class or variable name in python.

**Comment by jkrick** [comment]
This is great, I did not know about named tuples.  How does this mesh with the multi index data frame?  I can't yet quite conceptualize how to link these to the light curves.

**Comment by troyraen** [comment]
It would be a separate data structure from the multi-index dataframes. If you wanted to make a dataframe following the logic that's currently in the notebook, it could look something like this:

```python
import pandas as pd
from data_structures import MultiIndexDFObject

df_lc = MultiIndexDFObject()
for singleobj in objects_list:
    dfsingle = pd.DataFrame({
        "objectid": singleobj.id,
        "label": singleobj.label
        "band": <source band>,
        "flux": <source flux>, 
        "err": <source error>, 
        "time": <source time>, 
    })
    df_lc.append(dfsingle.set_index(["objectid","label", "band", "time"]))
```

**Comment by jkrick** [comment]
I think I am in favor of actually making this change.  Mostly because I do think it is better downstream to have the objects linked to the light curves, and would probably be good for me to actually implement it under the theory that actually doing something re-enforces those neural pathways better than just reading about it.  

I could pretty easily be persuaded to not make the changes under the "if it ain't broke..." theory, so let me know what you think......

Trying to think about this, changes required would be:
1)  write a sample_selection function which creates the `namedtuple`.  Needs to be outside of clean_sample since this doesn't always get run. ie.,for testing I only run the yang sample without running clean_sample.
2) update the functions in each archive call when generating the MultiIndexDFObject to use "objectid":singlobj.id, and "label":singlobj.label (as clarified above)
3) update the functions in each archive call to loop over objects_list instead of coords_list, and then how they actually grab the ra and decs would change syntax.
4) update the functions in each archive call to take the `namedtuple` as input instead of coords_list and labels_list
5) work on plotting function ( I don't have this one in my head well enough to know what changes will need to be made here. )

**Comment by troyraen** [comment]
I think that's generally right. Basically all the function signatures would also change (since `coords_list`, `labels_list`, and `object_names` would no longer be separate arguments) and documentation would need updating. It might (?) involve more changes than you realize up front. Could always start to get a sense of what it would entail, and be prepared to hit the "eject" button early if it starts to seem like too much for a notebook that isn't broken.

BTW, 

> for testing I only run the yang sample without running clean_sample

I think the Yang sample returns 31 objects, `clean_sample` removes one (thinking it's a duplicate) and returns 30 objects.

**Comment by jkrick** [comment]
after using the data structure for a while; here is an updated suggestion from @troyraen copied here from slack:

I think it makes sense to keep a separate data structure for “objects” that includes their coordinates, label, objectid, and redshift. The current coords_list is a start, but currently only includes the objectid and coordinates. I think we should add the labels and redshift. This would allow us to get rid of the labels_list (which is problematic and confusing, but I’ll refrain from elaborating unless requested).
The coords_list is a list of tuples, one per object. Each tuple has: (objectid, skycoords). The simplest change would be to add items to the tuple so that it contains: (objectid, skycoords, label, redshift). Refactoring current code would be required in order to get the label from this tuple rather than from a separate list.
From there, it would be pretty easy to make these named tuples, which retain all the properties of regular tuples (and so will not break existing code) and add the ability to access tuple elements using the dot notation (e.g., myobject.redshift would be equivalent to myobject[3]). The dot notation is a convenient way to access tuple elements that is more clear and less error prone (no need to remember which element position stores the redshift). However, given that a lot of code is already written based on regular tuples, it’s not clear to me that this would help us much unless we want to refactor the existing code for clarity.
In either case (tuple or named tuple), it would be easy to turn that coords_list into a dataframe. We could leave the existing code as-is (using the list) and turn it into a dataframe at whatever point the benefits of a dataframe are useful (perhaps in the ML notebook).

**Comment by jkrick** [comment]
At the same time that we address this issue, it makes sense to consider cleaning up the considerable gymnastics that our coordinates go through.  At times they need to be tables, at times lists, at times they go through tables to get to lists then back to tables to be saved (then back to lists to be used).  Is there some way to streamline this?  I am the culprit in just using whatever is necessary to get to the next point in the code rather than thinking through how to make this all cleaner.

**Comment by bsipocz** [comment]
This very same problem came up while I was doing #148, and would in fact suggest to `clean_sample` to return a Table than go into the chaotic mess of tupples and multiple lists. What I see as an advantage for tables:

- all that info could be linked (e.g. in a previous version of the notebook the coord_list and label_list got diverged. That particular bug has been fixed, but having multiple list would not be fail safe for future similar issues)
- it's very easy to add a new column to the table, be it redshift, or anything
- it's very easy to index, and select only relevant column(s) -- I think it's simpler to use it than a namedtuple, but certainly not more difficult

**Comment by zoghbi-a** [comment]
> This very same problem came up while I was doing #148, and would in fact suggest to `clean_sample` to return a Table than go into the chaotic mess of tupples and multiple lists. What I see as an advantage for tables:
> 
> * all that info could be linked (e.g. in a previous version of the notebook the coord_list and label_list got diverged. That particular bug has been fixed, but having multiple list would not be fail safe for future similar issues)
> * it's very easy to add a new column to the table, be it redshift, or anything
> * it's very easy to index, and select only relevant column(s) -- I think it's simpler to use it than a namedtuple, but certainly not more difficult

Thanks @jkrick for pointing me to this thread.
I think it is not just `clean_sample`, but also other parts in `sample_selection.py` don't scale up well if you increase the number of sources from SDSS. My suggestion over slack was to use tables of ra,dec instead of lists of SkyCoord to hold the sample.
It may require small changes in many places. I am happy to help if needed.

**Comment by troyraen** [comment]
I agree that an astropy Table would fix the biggest issues we currently have with `coords_list` and `labels_list` and that it will probably be better than a named tuple here because of the various ways this data gets used. (Of course, neither a named tuple nor a Table is inherently better or easier to use as this will depend on the specific use case.) My recent suggestion to just add the labels and redshifts to the tuples that already exist in `coords_list` was motivated by trying to find the simplest solution given the code that's already here. Glad to see that @bsipocz is pushing ahead with the Table. I imagine this may be a significant refactor -- let me know if you want my help.

**Comment by bsipocz** [comment]
> I imagine this may be a significant refactor -- let me know if you want my help.

Indeed, I pushed a draft with where I'm at the moment (#156), unfortunately it cannot be done in an incremental way (or it would need some inelegant hacks). 
So, while I'm doing the refactor, and I run into a couple of separate issues, I try to separate them out to more trivial PRs, so those can go in easier without breaking functionality (#157).

**Comment by bsipocz** [comment]
> let me know if you want my help.

Oh, thanks. I wonder what the most efficient way to tackle this while 3 of us are working on the same notebook. Maybe super small quick PRs are the way that we review for each other quickly? If you have suggestions, let me know. e.g. #157 started as a small fix for the tqdm iterations, then it got out of hands with a lot of other things. Would you prefer to try to keep things smaller, or it's still fine as that size level?

**Comment by troyraen** [comment]
> Would you prefer to try to keep things smaller, or it's still fine as that size level?

I'm not currently doing any major work with this so it's fine with me at that size level.

**Comment by jkrick** [comment]
> I wonder what the most efficient way to tackle this while 3 of us are working on the same notebook.

I can easily leave this notebook alone for a while and work on the ML notebook so that I am not doing any commits and creating any conflicts with the speedup work.  Then you can work at whatever size scale is best for you.

**Comment by jkrick** [comment]
closing with PR #171
