### ISSUE TITLE
uniformly handle the case where there are no archive matches for coords_list 

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#138]
Currently the Heasarc and TESS/Kepler/K2 get_lightcurves functions return empty data frames if no matches are found in the archives.  The gaia_get_lightcurves function will throw an error if this happens (good thing they have so much data!).  Other archive calls need to be checked and a uniform solution implemented.

Options appear to be
- return and empty data frame
- return `none` and edit `multiindexdf.append` to ignore `none`

**Comment by afaisst** [comment]
It’s probably good to know that no source was matched. I therefore like “none”.

From: jkrick ***@***.***>
Date: Monday, September 11, 2023 at 1:00 PM
To: fornax-navo/fornax-demo-notebooks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fornax-navo/fornax-demo-notebooks] uniformly handle the case where there are no archive matches for coords_list (Issue #138)

Currently the Heasarc and TESS/Kepler/K2 get_lightcurves functions return empty data frames if no matches are found in the archives. The gaia_get_lightcurves function will throw an error if this happens (good thing they have so much data!). Other archive calls need to be checked and a uniform solution implemented.

Options appear to be

  *   return and empty data frame
  *   return none and edit multiindexdf.append to ignore none

**Comment by troyraen** [comment]
Now that I'm digging into the code I see that it's going to be easier to have all the functions return an empty dataframe rather than `None`. Most of the functions (6 out of 8) already do this, so the code changes are much simpler if we just make them all do this. Also, this might be better for downstream users -- see https://github.com/fornax-navo/fornax-demo-notebooks/pull/154#discussion_r1343154419 from @bsipocz about what astroquery does and why. We're handling everything under the hood, so we can accommodate either without issue, but "downstream users" might take our code out of the notebook/scripts and into their own code and then may have an easier time handling empty dataframes rather than `None`. 

It doesn't deeply matter what we choose. If anyone has a strong preference for `None`, speak up, otherwise I'll continue with the empty dataframe

**Comment by jkrick** [comment]
My preference is to go with your and Brigitta's opinions, because you have thought about it the most.

**Comment by bsipocz** [comment]
> My preference is to go with your and Brigitta's opinions, because you have thought about it the most.

Disclaimer: I've certainly thought about a lot in the astroquery situation, where we have a lot of downstream users, and frequent server outage (with ~50 modules, server outages become frequent, resulting in lot of unrelated bugreports).
However, the situation here is different, so either case could/should work. I still slightly prefer the empty results, as it carries the extra information about a successful query, while None or an error could mean a query that hasn't yet starter or one that run into some issues.
