### ISSUE TITLE
warnings on parallel section

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#174]
check the warnings that appear only for the parallel call (deprecation warnings) and make sure we don't need to do anything about these.

**Comment by troyraen** [comment]
I saw a couple that were related to concatenating empty dataframes, so this is probably on me to take a closer look.

**Comment by troyraen** [comment]
Here's a list of things I'm noticing:

General:

- [ ] Warnings are being hidden in the serial section due to the following line in the imports cell. Why is it here? I would like to remove it.
  ```
  warnings.filterwarnings('ignore')
  ```
- [ ] Warning about pandas `concat`:
  ```
  /home/jovyan/fdn-tmp/light_curves/code_src/data_structures.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data = pd.concat([self.data, x])
  ```

heasarc_functions.py:

- [ ] Four warnings about units:
  ```
  WARNING: UnitsWarning: Unit 'degree' not supported by the VOUnit standard.  [astropy.units.format.vounit]
  WARNING:astroquery:UnitsWarning: Unit 'degree' not supported by the VOUnit standard. 
  WARNING: UnitsWarning: Unit 'mjd' not supported by the VOUnit standard. Did you mean MD, MJ, Md, mD, mJ or md? [astropy.units.format.vounit]
  WARNING:astroquery:UnitsWarning: Unit 'mjd' not supported by the VOUnit standard. Did you mean MD, MJ, Md, mD, mJ or md?
  ```

TESS_Kepler_functions.py:

- [x] "ERROR" when lightkurve finds no data for an object. This is not a real error (cannot be caught with try/except). It appears to just be a print statement generated by the function `lightkurve.search_lightcurve`. I spent a little time looking, but couldn't find a way to silence it other than completely capturing the stdout. I'm guessing we don't want to do that.

**Comment by troyraen** [comment]
> are the heasarc ones coming from heasarc serving non-VO units in the returned data?

I went back to check but can no longer reproduce the warnings. Not sure whether we fixed something or HEASARC did.

I also no longer see any lightkurve "ERROR"s.

Can someone double check and see if you get any errors in the parallel section (@jkrick, @bsipocz)? If not, we're done here except that I would still like to remove the `filterwarnings` from imports cell, unless there are objections?

**Comment by troyraen** [comment]
> small change to the HCV_get_lightcurves to remove the line which prints out "no matches"?

- [ ] Yes, we can remove that and just replace it with `continue`. (Then the `else` line can go away as well, which will help simplify the code block.)

> add a comment to the bottom of the parallel cell which says the lightkurve errors are there but can be safely ignored?

- [ ] Yes

> plotting is throwing a lot of warnings.

- [ ] I'll check on this. In the past I've seen warnings there when using a very small sample (like 2 objects) but not with the default (Yang) sample. I'll look more closely.

I think I'll open a PR to address just the remaining stuff identified here (rather than adding them individually to #177).

**Comment by jkrick** [comment]
as of just now on the SMCE, plotting is not throwing a lot of warnings.
