### ISSUE TITLE
Make a script to run light curve functions at scale

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#195]
Update sample_lc.py to, e.g., use `sample_table`. (This is a script version of the parallel section of the notebook, meant to be called from command line, but has not been kept up to date.) Alternately, consider making the modules directly callable from the command line and write a .sh script to execute them. This should speed up bulk runs because ZTF could use multiple workers.

**Comment by jkrick** [comment]
Im renaming this issue to be more clear about what I think the goal of this issue is, but if I have misappropriated some other issue, please clarify.  I don't think we want to update an old script, I think we want a new functional script that runs the light curve notebook at scale.  For the time being, this should include ZTF, WISE, HEASARC, Icecube, and Gaia.  It should in the future be able to also run the MAST archive searches.
