### ISSUE TITLE
Filter out TESS light curves containing negative fluxes

### ISSUE THREAD

**Issue by troyraen** [fornax-navo/fornax-demo-notebooks#202]
Some TESS fluxes are negative. Is that ok, or do we want to filter those out?

For example, see SDSS objects 2, 21, 54, 70, 72, 81, and 94.

**Comment by bsipocz** [comment]
Are those fill in values for missing data or just random negative numbers?

**Comment by troyraen** [comment]
It's a wide range of negative numbers, not just one value encoding NaN.

**Comment by bsipocz** [comment]
I would ping the ST people on the navo slack, I think that has a higher chance of being noticed and getting some insight.

**Comment by jkrick** [comment]
From the TESS documentation: "When converting to magnitudes, we only use data points with signal-to-noise ratio = cts_per_s/e_cts_per_s > 3.0. Points with a signal-to-noise ratio below 3, including all negative fluxes, are converted to magnitude upper limits with the formula -2.5log10(3*e_cts_per_s) + 20.44. Negative fluxes are due to either an overestimated background or statistical noise that fluctuates below the background level. Upper limits are marked in the light curve files by setting the magnitude uncertainty to 99.9."

https://tess.mit.edu/public/tesstransients/pages/readme.html#:~:text=Negative%20fluxes%20are%20due%20to,the%20magnitude%20uncertainty%20to%2099.9%20.

It makes sense to me that these would be low SNR detections because TESS was designed to measure stellar variations, and so does better with sources brighter than most AGN.  

So, yes, ideally, we would filter out points with magnitude_uncertainty > 99 as non-detections.

**Comment by troyraen** [comment]
Thanks for finding the docs. I don't see the magnitude uncertainty ("e_mag") in the columns that are returned by lightkurve, but I don't see a reason to track that down. Seems fine to just drop points with negative flux.

**Comment by troyraen** [comment]
Hmm, there are also NaNs in here in addition to negative values. So now it's not clear to me what to do. I think we decided to keep NaNs in #203. I don't see a good reason to keep one but drop the other. Seems inconsistent. Thoughts?

(I'm trying to do the right thing here, but also not over-think it. The actual code change to drop rows is simple, if that's really what we want to do.)

**Comment by jkrick** [comment]
interesting.... We decided in #203 that ideally we would drop the "invalid" photometry points (either NaN or negative) in each individual function, but it wasn't worth actually going into each function. 

How about a twofold approach?
1) let's leave this issue open (cringing just a little) to drop the negatives and NaNs when we next touch this function, ie., when MAST helps us figure out how to do this work more efficiently?

2) @troyraen  Do we need to change anything in the plotting function now to handle both negatives and NaN's or is that already done?

**Comment by troyraen** [comment]
> We decided in https://github.com/fornax-navo/fornax-demo-notebooks/issues/203 that ideally we would drop the "invalid" photometry points (either NaN or negative) in each individual function, but it wasn't worth actually going into each function.

Ah, ok, I misunderstood. I'm happy to just drop both. This is a very simple PR and I've already done the work, committed and ready to push. How about I just finish that and then we can close this?

**Comment by troyraen** [comment]
Oh, and the plotting function can handle both NaNs and negative fluxes now, so we don't *need* to do anything from a coding perspective. (Plotting will throw an error if given negative error values, but TESS doesn't have any of those as far as I can tell.)

**Comment by jkrick** [comment]
yes, if you have already done the work, lets make it happen!
