### ISSUE TITLE
Add ~2 sentence summary of the project for the landing page

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-demo-notebooks#274]
#272 has removed the inclusion of the repo readme in the rendered documentation, but now the landing page looks weird with starting off with two lists without anything else.

I think a title and a 1-2 sentence summary would still be useful to be included at the very top (and that all should go at the top of the [`index.md`](https://github.com/fornax-navo/fornax-demo-notebooks/blob/main/index.md) file)

**Comment by jkrick** [comment]
Here is the 1 sentence summary @vandesai1  pointed me to from https://pcos.gsfc.nasa.gov/Fornax/

"NASA Astrophysics is developing the Fornax Initiative, a cloud-based system that brings together data, software, and computing so that researchers can focus on science."

@bsipocz can you please put this where it needs to go?
