### ISSUE TITLE
Switch to markdown for notebooks

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-demo-notebooks#36]
I find it very difficult to do proper development and contained commits for the notebook, and regularly end up manually editing out JSON syntax errors. It's also very difficult to review changes in the notebook.

If we don't plan to store executed outputs in the notebooks, then I would strongly suggest switching to MyST markdown flavour for the repo.

cc @jkrick @troyraen

**Comment by troyraen** [comment]
I agree 100%

**Comment by jkrick** [comment]
Based on your GISS talk last week, I would guess we do want rendered notebooks as a final product so that the resulting plots/tables/whatevers can be shown along with a functional code.

I am willing to try switching to markdown, I just need some instruction on how to get that setup and work with it.

**Comment by bsipocz** [comment]
I'll try to get to it by the second half of the week. As for the rendering I'm not sure yet how to do it, where to actually run the code, so it may take a little bit more time to come up with a deployable solution. But it's something totally on my radar for the Q4 deliverable.

**Comment by jkrick** [comment]
closed as part of PR #167 

Jupytext is now functional on both ISP and SMCE
