### ISSUE TITLE
ModuleNotFound error

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-demo-notebooks#61]
running on IRSA SP, I am getting a ModuleNotFound error for the `import fornax` statement in the section on getting IRAC data from the cloud

**Comment by troyraen** [comment]
Is this something that has worked for you before on the IRSA SP? As I understand it, the notebook is looking for that module in a local directory, and each user has to manually do a `git clone` to put it there. (This is because @bsipocz had to patch in a fix for the `fornax-cloud-access-API` that is not yet available in their live version.) Basically it expects the root directories of both the `fornax-cloud-access-API` repo and this `fornax-demo-notebooks` repo to be sitting next to each other in your local tree.

If this has never worked for you on the IRSA SP (or you've never tried), then you probably need to clone it to that location using:

```
git clone https://github.com/bsipocz/fornax-cloud-access-API --depth=1 -b handler_return
```

If this did work for you previously, then my first guess is that you're running the notebook from a location that is different than expected. It's looking for `'../../fornax-cloud-access-API'`, relative to its current working directory.

**Comment by troyraen** [comment]
related to #33

**Comment by jkrick** [comment]
You are correct, I have never done the git clone.  So should I do the git clone in my home directory or in the fornax-demo-notebooks/forced_photometry?

**Comment by troyraen** [comment]
Your home directory, assuming "home" is the _parent_-directory of fornax-demo-notebooks.

**Comment by bsipocz** [comment]
Yes, sorry about the cloning stuff. This should eventually end up in the image itself (and in pyvo), but for now it's on the user level.

Also note, that the branch got merged, so no need to install the branch, you can do the slightly simpler:
`git clone https://github.com/fornax-navo/fornax-cloud-access-API --depth=1`

**Comment by bsipocz** [comment]
(and while this migrates into it's final place, we need to document the howto, thus I added the label and suggest to close this when enough info is included in the notebook itself)

**Comment by jkrick** [comment]
Sorry, I didn't actually read all the comments at the top of the cell.  That was my fault.  My suggestion is that it should clearly state something like "you need to git clone blah blah from the directory above your fornac-demo-notebook directory"  And then when this gets taken care of later we can just remove that comment.
