### ISSUE TITLE
Green Sample

### ISSUE THREAD

**Issue by xoubish** [fornax-navo/fornax-demo-notebooks#90]
get_green_sample gives the 403 forbidden error

**Comment by jkrick** [comment]
The problem appears to be that the journal gives an expiration date to the html version of all full tables (those that don't fit within their formatted pages).  We use that html link to read in the table.
@bsipocz submitted an astropy [issue](https://github.com/astropy/astropy/issues/14556) to help with this.  This will not be the fastest way to solve this problem.

I submitted a request to Vizier to add the table to their collection so that we could use `astroquery` to access the table in its entirety.
